name: Continuous Deployment to Remote Server
on:
  workflow_dispatch:

env:
  TEST_VAR_1: Hello_There


jobs:
  remote_deployment:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Connect and Deploy on Remote Server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.REMOTE_PRIV_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: echo $TEST_VAR_1
